version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./app:/var/www/html
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    volumes:
      - ./app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin12345
      - MYSQL_PASSWORD=admin12345
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - UPLOAD_LIMIT=750M
    depends_on:
      - db