version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT2}:433"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./app:/var/www/html
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    volumes:
      - ./app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYAMDIN_PORT}:80"
    environment:
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
    depends_on:
      - db